# Generated by Django 3.2.5 on 2022-11-26 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0002_applicant_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='description',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='img',
            field=models.ImageField(upload_to='img_applicant'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='position',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
