# Generated by Django 3.2.5 on 2022-11-30 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0004_auto_20221126_1555'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
