# Generated by Django 3.2.5 on 2022-11-30 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0005_compform'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompForm',
        ),
    ]
