# Generated by Django 3.2.5 on 2022-11-30 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0007_competence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='img',
            field=models.ImageField(upload_to='static/image/img_applicant'),
        ),
        migrations.AlterField(
            model_name='competence',
            name='C1',
            field=models.CharField(choices=[('1', 1), ('2', 2), ('3', 3)], default=1, max_length=1),
        ),
        migrations.AlterField(
            model_name='competence',
            name='C10',
            field=models.CharField(choices=[('1', 1), ('2', 2), ('3', 3)], default=1, max_length=1),
        ),
        migrations.AlterField(
            model_name='competence',
            name='C11',
            field=models.CharField(choices=[('1', 1), ('2', 2), ('3', 3)], default=1, max_length=1),
        ),
        migrations.AlterField(
            model_name='competence',
            name='C12',
            field=models.CharField(choices=[('1', 1), ('2', 2), ('3', 3)], default=1, max_length=1),
        ),
        migrations.AlterField(
            model_name='competence',
            name='C13',
            field=models.CharField(choices=[('1', 1), ('2', 2), ('3', 3)], default=1, max_length=1),
        ),
        migrations.AlterField(
            model_name='competence',
            name='C14',
            field=models.CharField(choices=[('1', 1), ('2', 2), ('3', 3)], default=1, max_length=1),
        ),
        migrations.AlterField(
            model_name='competence',
            name='C15',
            field=models.CharField(choices=[('1', 1), ('2', 2), ('3', 3)], default=1, max_length=1),
        ),
        migrations.AlterField(
            model_name='competence',
            name='C16',
            field=models.CharField(choices=[('1', 1), ('2', 2), ('3', 3)], default=1, max_length=1),
        ),
        migrations.AlterField(
            model_name='competence',
            name='C17',
            field=models.CharField(choices=[('1', 1), ('2', 2), ('3', 3)], default=1, max_length=1),
        ),
        migrations.AlterField(
            model_name='competence',
            name='C18',
            field=models.CharField(choices=[('1', 1), ('2', 2), ('3', 3)], default=1, max_length=1),
        ),
        migrations.AlterField(
            model_name='competence',
            name='C2',
            field=models.CharField(choices=[('1', 1), ('2', 2), ('3', 3)], default=1, max_length=1),
        ),
        migrations.AlterField(
            model_name='competence',
            name='C3',
            field=models.CharField(choices=[('1', 1), ('2', 2), ('3', 3)], default=1, max_length=1),
        ),
        migrations.AlterField(
            model_name='competence',
            name='C4',
            field=models.CharField(choices=[('1', 1), ('2', 2), ('3', 3)], default=1, max_length=1),
        ),
        migrations.AlterField(
            model_name='competence',
            name='C5',
            field=models.CharField(choices=[('1', 1), ('2', 2), ('3', 3)], default=1, max_length=1),
        ),
        migrations.AlterField(
            model_name='competence',
            name='C6',
            field=models.CharField(choices=[('1', 1), ('2', 2), ('3', 3)], default=1, max_length=1),
        ),
        migrations.AlterField(
            model_name='competence',
            name='C7',
            field=models.CharField(choices=[('1', 1), ('2', 2), ('3', 3)], default=1, max_length=1),
        ),
        migrations.AlterField(
            model_name='competence',
            name='C8',
            field=models.CharField(choices=[('1', 1), ('2', 2), ('3', 3)], default=1, max_length=1),
        ),
        migrations.AlterField(
            model_name='competence',
            name='C9',
            field=models.CharField(choices=[('1', 1), ('2', 2), ('3', 3)], default=1, max_length=1),
        ),
    ]
