# Generated by Django 3.2.5 on 2022-11-30 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0008_auto_20221130_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='img',
            field=models.ImageField(upload_to='media/img_applicant'),
        ),
    ]
